language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=e97a82c846b5d577de6a269706baeb21602e3fcd00ab4c518fa1957a7a92e3de
matrix:
  include:
    - node_js : '12'

cache:
  directories: [node_modules]

install:
  npm install
after_success:
  npm run coverage
before_script:
  - curl -L https://codeclimate.com/downloads/test-reposrter-latest-linux-amd64> ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
